### ISSUE TITLE
bug from minter-explorer-api

### ISSUE THREAD

**Issue by urpyLLIKa** [MinterTeam/minter-explorer-extender#50]
ERROR #42703 column validator.name does not exist
need update initial scheme

**Comment by urpyLLIKa** [comment]
example query from https://github.com/MinterTeam/minter-explorer-api/commit/cd8622749732bbbc71be80f15c13fb7f72eacefa


SELECT 
"block_validator"."block_id", "block_validator"."validator_id", "block_validator"."signed", "validator"."id" AS "validator__id", "validator"."reward_address_id" 
AS "validator__reward_address_id", "validator"."owner_address_id" AS "validator__owner_address_id", "validator"."created_at_block_id" AS "validator__created_at_block_id
", "validator"."status" AS "validator__status", "validator"."commission" AS "validator__commission", "validator"."total_stake" AS "validator__total_stake", "validator".
"public_key" AS "validator__public_key", "validator"."name" AS "validator__name", "validator"."site_url" AS "validator__site_url", "validator"."icon_url" AS "validator_
_icon_url", "validator"."description" AS "validator__description", "validator"."meta_updated_at_block_id" AS "validator__meta_updated_at_block_id", "validator"."update_
at" AS "validator__update_at" FROM block_validator AS "block_validator" LEFT JOIN "validators" AS "validator" ON "validator"."id" = "block_validator"."validator_id" WHE
RE ("block_validator"."block_id" IN (5361, 5360, 5359, 5358, 5357, 5356, 5355, 5354, 5353, 5352, 5351, 5350, 5349, 5348, 5347, 5346, 5345, 5344, 5343, 5342, 5341, 5340,
5339, 5338, 5337, 5336, 5335, 5334, 5333, 5332, 5331, 5330, 5329, 5328, 5327, 5326, 5325, 5324, 5323, 5322, 5321, 5320, 5319, 5318, 5317, 5316, 5315, 5314, 5313, 5312)
)

**Comment by urpyLLIKa** [comment]
and  ERROR #42703 column validator.site_url does not exist too

SELECT "block_validator"."block_id", "block_validator"."validator_id", "block_validator"."signed", "validator"."id" AS "validator__id", "validator"."reward_address_id" AS "validator__reward_address_id", "validator"."owner_address_id" AS "validator__owner_address_id", "validator"."created_at_block_id" AS "validator__created_at_block_id", "validator"."status" AS "validator__status", "validator"."commission" AS "validator__commission", "validator"."total_stake" AS "validator__total_stake", "validator"."public_key" AS "validator__public_key", "validator"."name" AS "validator__name", "validator"."site_url" AS "validator__site_url", "validator"."icon_url" AS "validator__icon_url", "validator"."description" AS "validator__description", "validator"."meta_updated_at_block_id" AS "validator__meta_updated_at_block_id", "validator"."update_at" AS "validator__update_at" FROM block_validator AS "block_validator" LEFT JOIN "validators" AS "validator" ON "validator"."id" = "block_validator"."validator_id" WHERE ("block_validator"."block_id" IN (16373, 16372, 16371, 16370, 16369, 16368, 16367, 16366, 16365, 16364, 16363, 16362, 16361, 16360, 16359, 16358, 16357, 16356, 16355, 16354, 16353, 16352, 16351, 16350, 16349, 16348, 16347, 16346, 16345, 16344, 16343, 16342, 16341, 16340, 16339, 16338, 16337, 16336, 16335, 16334, 16333, 16332, 16331, 16330, 16329, 16328, 16327, 16326, 16325, 16324)) <nil>

**Comment by urpyLLIKa** [comment]
and icon_url, description, meta_updated_at_block_id

**Comment by urpyLLIKa** [comment]
and no info in meta then append

**Comment by shrpne** [comment]
@daniildulin

**Comment by daniildulin** [comment]
fixed
